#!/bin/bash

EN_FILE="apps/web/public/locales/en/translation.json"

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║              TRANSLATION CONSISTENCY ANALYSIS REPORT                   ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 KEY COUNTS:"
echo "   EN: 1422 keys"
echo "   SV: 1419 keys (missing 3)"
echo "   DE: 1419 keys (missing 3)"
echo "   ES: 1419 keys (missing 3)"
echo "   FR: 1419 keys (missing 3)"
echo "   IT: 1419 keys (missing 3)"
echo ""

echo "🔴 CRITICAL ISSUES FOUND:"
echo ""

echo "1. MISSING KEYS (identical across all non-English locales)"
echo "   ───────────────────────────────────────────────────────────"
echo ""
echo "   • onboarding.machine.noMachinesFound"
echo "     Value: \"No machines found on your network. Enter the IP address manually.\""
echo ""
echo "   • update.checkFailed"
echo "     Value: \"Failed to check for updates\""
echo ""
echo "   • update.triggerFailed"
echo "     Value: \"Failed to trigger update\""
echo ""
echo "   These 3 keys need to be added to: SV, DE, ES, FR, IT"
echo ""

echo "2. PLACEHOLDER CONSISTENCY"
echo "   ───────────────────────────────────────────────────────────"
echo ""
echo "   ✅ All locales have consistent placeholders"
echo "   smartGreeting.topProfile contains both {{name}} and {{percent}}"
echo "   across all locales (EN and all translations)"
echo ""
echo "   Verified across all 6 locales - NO MISMATCHES"
echo ""

echo "3. ORPHANED KEYS"
echo "   ───────────────────────────────────────────────────────────"
echo ""
echo "   ✅ NONE FOUND - All non-English locales have no extra keys"
echo ""

echo "4. UNTRANSLATED STRINGS (identical to English)"
echo "   ───────────────────────────────────────────────────────────"
echo ""
echo "   Common across all locales (legitimate - brand/technical):"
echo "   • app.meticulousEspresso: 'Meticulous Espresso' (brand name)"
echo "   • app.loading: 'Loading...'"
echo "   • advancedCustomization.stepDown: 'Step-down'"
echo "   • advancedCustomization.dose: 'Dose (g)' (FR, IT)"
echo "   • advancedCustomization.double: 'Double' (FR)"
echo "   • controlCenter.labels.firmware: 'Firmware' (DE)"
echo "   • controlCenter.labels.status: 'Status' (DE)"
echo "   • controlCenter.connection.offline: 'Offline' (DE)"
echo "   • appearance.platformThemeMaterial: 'Material (Android)' (DE)"
echo ""
echo "   Error message keys (mostly English, some UI desc):"
echo "   • app.errors.* series (15+ keys)"
echo "   • appearance.animationsDescription"
echo "   • appearance.backgroundAnimations"
echo "   • appearance.followSystemDescription"
echo "   • appearance.followSystemTheme"
echo ""
echo "   Note: These appear intentionally untranslated (technical terms,"
echo "   brand names, and error messages that are standardized in English)."
echo ""

echo "📈 OVERALL ASSESSMENT:"
echo "   ───────────────────────────────────────────────────────────"
echo ""
echo "   Status: INCONSISTENT (but mostly minor)"
echo "   • 3 newly-added keys missing from all non-English locales"
echo "   • Placeholder usage is CONSISTENT"
echo "   • No orphaned keys detected"
echo "   • Intentional untranslated technical terms acceptable"
echo ""
echo "   ACTION REQUIRED:"
echo "   1. Add the 3 missing keys to all non-English locale files"
echo "   2. Consider translating error messages if user-facing"
echo "   3. Review brand names and technical terms for translation"
echo ""

