import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Loader2, Sparkles, RefreshCw, XCircle } from "lucide-react";
import { parseStructuredAnalysis } from "@/lib/parseAnalysis";
import { SectionCard } from "@/components/SectionCard";

interface LlmAnalysisModalProps {
  isOpen: boolean;
  isLoading: boolean;
  analysisResult: string | null;
  error: string | null;
  onClose: () => void;
  onReAnalyze?: () => void;
  profileName?: string;
  shotDate?: string;
  isCached?: boolean;
}

export function LlmAnalysisModal({
  isOpen,
  isLoading,
  analysisResult,
  error,
  onClose,
  onReAnalyze,
  profileName,
  shotDate,
  isCached,
}: LlmAnalysisModalProps) {
  const { t } = useTranslation();
  const sections = useMemo(() => {
    if (!analysisResult) return [];
    return parseStructuredAnalysis(analysisResult);
  }, [analysisResult]);
  
  return (
    <Dialog open={isOpen} onOpenChange={(open) => {
      if (!open) onClose();
    }}>
      <DialogContent className="max-w-4xl h-[90vh] flex flex-col p-0 gap-0">
        <DialogHeader className="px-6 py-4 border-b shrink-0">
          <div className="flex items-center justify-between">
            <div>
              <DialogTitle className="flex items-center gap-2 text-xl">
                <Sparkles className="h-5 w-5 text-primary" />
                AI Shot Analysis
                {isCached && (
                  <Badge variant="secondary" className="ml-2">
                    Cached
                  </Badge>
                )}
              </DialogTitle>
              <DialogDescription className="mt-1">
                {profileName && shotDate && (
                  <span>{profileName} • {shotDate}</span>
                )}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>
        
        <div className="flex-1 overflow-y-auto px-6 py-4">
          {/* AI Disclaimer */}
          <Alert className="mb-6 bg-amber-500/10 border-amber-500/30">
            <Info className="h-4 w-4 text-amber-500" />
            <AlertDescription className="text-sm text-amber-700 dark:text-amber-400">
              This analysis is generated by AI based on shot data. Results should be used as guidance, 
              not absolute truth. Always trust your own taste preferences.
            </AlertDescription>
          </Alert>
          
          {/* Loading State */}
          {isLoading && (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <div className="relative">
                <Loader2 className="h-12 w-12 animate-spin text-primary" />
                <Sparkles className="h-5 w-5 text-primary absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
              </div>
              <div className="text-center space-y-1">
                <p className="text-lg font-medium">{t('llmAnalysis.analyzingTitle')}</p>
                <p className="text-sm text-muted-foreground">{t('llmAnalysis.analyzingDescription')}</p>
              </div>
            </div>
          )}
          
          {/* Error State */}
          {error && !isLoading && (
            <Alert variant="destructive" className="mb-4">
              <XCircle className="h-4 w-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          
          {/* Analysis Content */}
          {!isLoading && !error && sections.length > 0 && (
            <div className="space-y-6">
              {sections.map((section, index) => (
                <SectionCard key={index} section={section} />
              ))}
            </div>
          )}
          
          {/* Fallback: Raw content if no sections parsed */}
          {!isLoading && !error && sections.length === 0 && analysisResult && (
            <Card>
              <CardContent className="pt-6">
                <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap">
                  {analysisResult}
                </div>
              </CardContent>
            </Card>
          )}
          
          {/* No Content State */}
          {!isLoading && !error && !analysisResult && (
            <div className="flex flex-col items-center justify-center py-16 gap-4 text-muted-foreground">
              <Sparkles className="h-12 w-12 opacity-30" />
              <p className="text-lg">{t('llmAnalysis.noAnalysis')}</p>
            </div>
          )}
        </div>
        
        {/* Footer with Re-Analyze button */}
        {!isLoading && analysisResult && onReAnalyze && (
          <div className="px-6 py-3 border-t bg-muted/30 shrink-0">
            <div className="flex items-center justify-center">
              <Button 
                variant="outline" 
                size="sm" 
                onClick={onReAnalyze}
                className="gap-2"
              >
                <RefreshCw className="h-4 w-4" />
                Re-Analyze{isCached ? ' for Fresh Insights' : ''}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
